/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hcetin;

import java.io.File;
import java.io.IOException;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cetin
 */
public class NBayes extends javax.swing.JFrame {
    
    /**
     * Creates new form NBayes
     */
    private Veriler v;
    private int KategoriKolonu;
    private Object[] Siniflar;

    public NBayes() {
        initComponents();
        CModel.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabOzellikler = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblStat = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblNominal = new javax.swing.JTable();
        BtnVerileriGoster = new javax.swing.JButton();
        BtnAc = new javax.swing.JButton();
        BDosyaSec = new javax.swing.JButton();
        TDosyaYolu = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        BTestBaslat = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TEgtSetiYzdsi1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        CModel = new javax.swing.JComboBox();
        LBasarim = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LNitelikler = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CFiltre = new javax.swing.JComboBox();
        BFiltreUygula = new javax.swing.JButton();
        BtnVeriDagilimGoster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Naive Bayes Sınıflayıcı");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabOzellikler.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabOzellikler.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seçili Niteliğin Özellikleri"));

        TblStat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Minimum", null},
                {"Maksimum", null},
                {"Ortalama", null},
                {"Standart Sapma", null}
            },
            new String [] {
                "İstatistik", "Değer"
            }
        ));
        jScrollPane1.setViewportView(TblStat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        TabOzellikler.addTab("Nümerik", jPanel3);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Seçili Niteliğin Özellikleri"));

        TblNominal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TblNominal);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        TabOzellikler.addTab("Nominal", jPanel11);

        BtnVerileriGoster.setText("Veri Seti...");
        BtnVerileriGoster.setToolTipText("Veri tablosunu gösterir.");
        BtnVerileriGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerileriGosterActionPerformed(evt);
            }
        });

        BtnAc.setText("Aç");
        BtnAc.setToolTipText("Seçilen dosyanın belleğe yüklenmesini sağlar");
        BtnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAcActionPerformed(evt);
            }
        });

        BDosyaSec.setText("...");
        BDosyaSec.setToolTipText("Veri seti seçer");
        BDosyaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDosyaSecActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Başarım Testi"));

        BTestBaslat.setText("Başla");
        BTestBaslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTestBaslatActionPerformed(evt);
            }
        });

        jLabel18.setText("Eğitim Verisi %si:");

        TEgtSetiYzdsi1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TEgtSetiYzdsi1.setText("80");
        TEgtSetiYzdsi1.setToolTipText("Veri setinin ne kadarlık kısmının eğitim verisi olarak kullanılacağını yüzdelik oran olarak belirtin.");
        TEgtSetiYzdsi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("%");

        CModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sınıflayıcı Modelini Seçin", "Naive Bayes", "Karar Ağacı", "Yapay Sinir Ağları" }));

        LBasarim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBasarim.setText("Doğruluk:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(CModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TEgtSetiYzdsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addComponent(LBasarim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTestBaslat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(TEgtSetiYzdsi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(LBasarim)
                .addGap(19, 19, 19))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(BTestBaslat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nitelikler"));

        LNitelikler.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LNiteliklerValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(LNitelikler);

        jLabel5.setText("Toplam Örnek Sayısı:");

        jLabel4.setText("Nitelik Sayısı:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtre"));

        CFiltre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Uygulamak İstediğiniz Filtreyi Seçin", "Min-Max Normalizasyon", "Z-Score Normalizasyon", "Ondalık Ölçekleme ile Normalizasyon" }));

        BFiltreUygula.setText("Uygula");
        BFiltreUygula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFiltreUygulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CFiltre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BFiltreUygula)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFiltreUygula))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        BtnVeriDagilimGoster.setText("Veri Dağılımları");
        BtnVeriDagilimGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVeriDagilimGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TDosyaYolu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BDosyaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAc)
                        .addGap(18, 18, 18)
                        .addComponent(BtnVerileriGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnVeriDagilimGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TabOzellikler)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TDosyaYolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDosyaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAc)
                    .addComponent(BtnVerileriGoster)
                    .addComponent(BtnVeriDagilimGoster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabOzellikler))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAcActionPerformed
        Siniflar = new Object[]{"1","2","3","4","5","6","7"};
        //System.out.println("Veri seti yükleniyor. Lütfen bekleyin...");
        KategoriKolonu = 13;
        try {
            Object[] sutunlar = new Object[]{"Elevation","Aspect","Slope",
                                "HorDistHyd", "VerDistHyd", "HorDistRws",
                                "Hshd9Am","HshdNoon","Hshd3Pm",
                                "HorDistFirePt","WildnArea","SoilType",
                                "CoverType"};
            
            v = new Veriler(TDosyaYolu.getText(), sutunlar, KategoriKolonu);
            LNitelikler.setListData(v.KolonBasliklari());
            jLabel4.setText("Nitelik Sayısı: "+Integer.toString(v.Tablolar.VeriTablosuAl().getColumnCount()));
            jLabel5.setText("Toplam Örnek Sayısı: "+Integer.toString(v.Tablolar.VeriTablosuAl().getRowCount()));
            //System.out.println("Veri seti başarılı bir şekilde yüklendi.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Veri dosyası okunurken hata oluştu: "+ex,"Hata!", JOptionPane.ERROR_MESSAGE);            
            System.out.println("Veri dosyası okunurken hata oluştu!: "+ex);
        }
    }//GEN-LAST:event_BtnAcActionPerformed

    private void BDosyaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDosyaSecActionPerformed
        JFileChooser dosec = new JFileChooser("./data");
        dosec.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".data") || f.isDirectory();
            }

            @Override
            public String getDescription() {
                return ".data dosyaları";
            }
        });
        int d = dosec.showOpenDialog(null);
        if (d == JFileChooser.APPROVE_OPTION) {
            TDosyaYolu.setText(dosec.getSelectedFile().toString());
        }
    }//GEN-LAST:event_BDosyaSecActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void BtnVerileriGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerileriGosterActionPerformed
        JFrame goster = new JFrame("Veri Seti");
        goster.setSize(800, 600);
        JTable t = new JTable(v.Tablolar.VeriTablosuAl());
        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        JScrollPane sp = new JScrollPane(t);
        goster.add(sp);
        goster.setVisible(true);
    }//GEN-LAST:event_BtnVerileriGosterActionPerformed

    private void LNiteliklerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LNiteliklerValueChanged
        int idx = LNitelikler.getSelectedIndex();
        int katidx = KategoriKolonu-1;
        if (idx == katidx){
            TabOzellikler.setSelectedIndex(1);
            DefaultTableModel nomtbl = new DefaultTableModel();
            nomtbl.addColumn("Sıra");
            nomtbl.addColumn("Etiket");
            nomtbl.addColumn("Miktar (Adet)");
            for (int i=0; i<Siniflar.length; i++)
                nomtbl.addRow(new Object[]{i,Siniflar[i], Mat.Say(v.SutunuAl(katidx).toArray(), Siniflar[i])});
            
            TblNominal.setModel(nomtbl);
        } else {
            TabOzellikler.setSelectedIndex(0);
            DefaultTableModel statbl = new DefaultTableModel();
            statbl.addColumn("İstatistik");
            statbl.addColumn("Değer");
            statbl.addRow(new Object[]{"Minimum",v.Dagilimlar.SutunMinAl(idx)});
            statbl.addRow(new Object[]{"Maksimum",v.Dagilimlar.SutunMaxAl(idx)});
            statbl.addRow(new Object[]{"Ortalama",v.Dagilimlar.SutunOrtAl(idx)});
            statbl.addRow(new Object[]{"Standart Sapma",Math.sqrt(v.Dagilimlar.SutunVarAl(idx))});
            TblStat.setModel(statbl);
        }
    }//GEN-LAST:event_LNiteliklerValueChanged

    private void BTestBaslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTestBaslatActionPerformed
        int idx = CModel.getSelectedIndex();
        switch (idx) {
            case 0:
                System.out.println("Lütfen bir sınıflayıcı modeli seçin!");
                JOptionPane.showMessageDialog(null, "Lütfen bir sınıflayıcı modeli seçin!", super.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                break;
            case 1:
                //new Console(CiktiAlani);
                NaiveBayes tbayes = new NaiveBayes(Siniflar, KategoriKolonu, v.Tablolar.DagilimTablosuAl());
                
                tbayes.NitelikleriAyarla(v.KolonBasliklari());
                tbayes.EgitimSetiOraniAyarla(TEgtSetiYzdsi1.getText());
                tbayes.ModeliEgit(v.Tablolar.VeriTablosuAl());
                Double sonuc = tbayes.Test();
                LBasarim.setText("Doğruluk: %"+sonuc.toString());
                System.out.println("Doğruluk: %"+sonuc.toString());
                //new Console(Konsol);
                JOptionPane.showMessageDialog(null, "Model Başarımı: "+sonuc.toString(), super.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                System.out.println("Seçtiğiniz model henüz hazır değil.");
                JOptionPane.showMessageDialog(null, "Bu model henüz hazır değil!", super.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                break;
        }


    }//GEN-LAST:event_BTestBaslatActionPerformed

    private void BFiltreUygulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFiltreUygulaActionPerformed
        int idx = CFiltre.getSelectedIndex();
        switch(idx){
            case 1:
                v.Filtreler.MinMaxUygula(0.0, 1.0);
                break;
            case 2:
                v.Filtreler.ZScoreUygula();
                break;
            case 3:
                break;
            default:
                JOptionPane.showMessageDialog(null,"Lütfen filtre listesinden bir filtre seçin.",super.getTitle(),JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_BFiltreUygulaActionPerformed

    private void BtnVeriDagilimGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVeriDagilimGosterActionPerformed
        JFrame goster = new JFrame("Veri Dağılımları");
        goster.setSize(800, 600);
        JTable t = new JTable(v.Tablolar.DagilimTablosuAl());
        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        JScrollPane sp = new JScrollPane(t);
        goster.add(sp);
        goster.setVisible(true);
    }//GEN-LAST:event_BtnVeriDagilimGosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NBayes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NBayes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDosyaSec;
    private javax.swing.JButton BFiltreUygula;
    private javax.swing.JButton BTestBaslat;
    private javax.swing.JButton BtnAc;
    private javax.swing.JButton BtnVeriDagilimGoster;
    private javax.swing.JButton BtnVerileriGoster;
    private javax.swing.JComboBox CFiltre;
    private javax.swing.JComboBox CModel;
    private javax.swing.JLabel LBasarim;
    private javax.swing.JList LNitelikler;
    private javax.swing.JTextField TDosyaYolu;
    private javax.swing.JTextField TEgtSetiYzdsi1;
    private javax.swing.JTabbedPane TabOzellikler;
    private javax.swing.JTable TblNominal;
    private javax.swing.JTable TblStat;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
